[package]
name = "nt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
sysinfo = "0.37.2"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "time"] }

[[bin]]
name = "nt"
path = "src/main.rs"
